
version: '3'
services:
  flask: 
    container_name: 'flask-container'
    build:
      context: .
      dockerfile: ./Dockerfile
    
    env_file: ./.env
    ports:
      - :8000
    volumes:
      - flask_conf:/var/www/html/flask
    
    networks:
      - flask-net
      
  

networks:
  flask-net:
   external: true

volumes:
  flask_conf:
   external: true
    
     
