apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: flask-conf
  name: flask-conf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
