apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    service: flask
spec:
  selector:
    service: flask
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
