apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: mariadb-data
  name: mariadb-data
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: 10Gi
  storageClassName: local-path


