apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
       service: mariadb
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: shared-env
                optional: false

          image: mariadb:latest
          name: mariadb
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-data
      restartPolicy: Always
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
