apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: nginx-conf
  name: nginx-conf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
