apiVersion: v1
kind: Service
metadata:
  labels:
    service: nginx
  name: nginx

spec:
  selector:
    service: nginx
  ports:
    - name: "80"
      port: 80
      nodePort: 30000
  type: NodePort
