apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: nginx
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
       service: nginx
    spec:
      containers:
        - image: hamzaleghari/flask-nginx:latest
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: nginx-cache
              mountPropagation: HostToContainer

      restartPolicy: Always


      volumes:
        - name: nginx-cache
          persistentVolumeClaim:
            claimName: nginx-cache
       

