apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: nginx-cache
  name: nginx-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
